### ISSUE TITLE
Hello, FluxLoader

### ISSUE THREAD

**Issue by nordron01** [Deknil/Deknil#1]
Привет у тебя остались исходники для FluxLoader?

**Comment by Brov3r** [comment]
Привет, да - [ссылка](https://github.com/Deknil/FluxLoader)

**Comment by nordron01** [comment]
а куда старые разработки делись?)  и плагины

**Comment by Brov3r** [comment]
Из-за отсутствия интереса со стороны сообщества PZ было принято решение прекратить все разработки, все-таки моддинг на Lua закрепился сильнее, чем я думал :c

**Comment by nordron01** [comment]
хзаха на LUA античит не напишешь, там пересобирать ванильные java нужно, чтобы ловить ивенты читаков, вот например сегодня ночью кто-то запустил скрипт и на сервере всю карту заприватили рандомными значениями, по сути сервер теперь не играбельный, эти разработки мне частично помогали снимать логирование с игры и отлавливать негодных, если бы дальше проект развивался наверно стал бы очень полезным
